pipeline:
  build:
    image: plugins/docker
    storage_driver: overlay
    repo: kube-registry.kube-system:9000/yoyostile/yoyostile
    registry: kube-registry.kube-system:9000
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - latest
