pipeline:
  build:
    image: plugins/docker
    storage_driver: overlay
    repo: registry.gitlab.com/yoyostile/yoyostile.de
    registry: registry.gitlab.com
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - latest
    secrets: [registry.gitlab.com]
    when:
      event: push

  test:
    image: alpine
    commands:
      - cat /etc/hosts
      - cat /etc/resolv.conf
      - ping -c 1 github.com
      - curl -vvv https://github.com
    when:
      status: [failure, success]
