pipeline:
  build:
    image: plugins/docker
    storage_driver: overlay
    repo: registry.gitlab.com/yoyostile/yoyostile.de
    registry: registry.gitlab.com
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - latest
    when:
      event: push
      branch: [master]
